name: tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy .env
        run: cp .env.example .env
      - name: Build containers
        run: |
          docker-compose -f docker-compose.test.yml build fpm node
          docker-compose -f docker-compose.test.yml up -d redis
      - name: Install Packages
        run: |
          docker-compose -f docker-compose.test.yml run --rm fpm composer install
          docker-compose -f docker-compose.test.yml run --rm node yarn
      - name: php-cs-fixer Permissions
        run: |
          chmod +x tools/php-cs-fixer/vendor/bin/php-cs-fixer
      - name: Run lint/prettier checks
        run: |
          docker-compose -f docker-compose.test.yml run --rm fpm composer fix-cs-check
          docker-compose -f docker-compose.test.yml run --rm node yarn build
          docker-compose -f docker-compose.test.yml run --rm node yarn prettier:check
      - name: Generate Key
        run: |
          docker-compose -f docker-compose.test.yml run --rm fpm php artisan key:generate
      - name: Run PHPUnit Tests
        run: |
          docker-compose -f docker-compose.test.yml run --rm fpm php artisan test --coverage --min=95
