name: tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy .env
        run: cp .env.example .env
      - name: Install Composer Packages
        run: |
          docker-compose run --rm fpm composer install
      - name: php-cs-fixer Permissions
        run: |
          chmod +x tools/php-cs-fixer/vendor/bin/php-cs-fixer
      - name: Build containers
        run: docker-compose build
      - name: Install Node Packages
        run: |
          docker-compose run --rm web yarn
      - name: Run lint/prettier checks
        run: |
          docker-compose run --rm fpm composer fix-cs-check
          docker-compose run --rm web yarn prettier:check
      - name: Generate Key
        run: |
          docker-compose run --rm fpm php artisan key:generate
      - name: Run PHPUnit Tests
        run: |
          docker-compose run --rm fpm php artisan test --coverage --min=95
